### ISSUE TITLE
Stuff RangerMauve is working on

### ISSUE THREAD

**Issue by RangerMauve** [datproject/planning#7]
Just wanted to have a place to keep track of the stuff I'm working on and what I plan to work on

- [x] dat-store: Support sharing folders if the store service is running locally https://github.com/datproject/dat-store/issues/9
- [x] Network debugging documentation: what steps should people take to when they can't load data
- [x] Fix up [Dat-Archive-Web](http://github.com/RangerMauve/dat-archive-web)
- [x] Fix issues with file watching in dat-store
- [x] Fix dat-js not advertising Dats on the network. https://github.com/RangerMauve/discovery-swarm-stream/issues/7
- [x] Enable dat-store to sync changes from a remote dat to local FS (like dat clone)

## Priorities
- [x] [Minimal Spanning Tree](https://github.com/RangerMauve/mostly-minimal-spanning-tree) (wireline funding)
- [x] Web support in [hyperdiscovery](https://github.com/datproject/hyperdiscovery/issues/33)
- [x] Dat SDK
  - [x] Draft up a repo for what goes into it (library/feed/archive/swarm/gateway)
  - [ ] Create demo app with documentation on how the different parts work 
  - [x] Create documentation for individual tools in the SDK
- [x] Integrate the SDK with dat-store
- [ ] hypercore support for dat-store
- [ ] UI for managing dat-stores (or hashbase if it adds CORS) published to Dat
- [ ] Dat 2 - SDK integration / etc
  - [x] hyperswarm-proxy
  - [ ] hyperswarm-web
  - [ ] Support base32 in [dat-encoding](https://github.com/dat-land/dat-encoding/) and [dat-dns](https://github.com/datprotocol/dat-dns)
  - [ ] unit tests for hyperdrive replication
  - [ ] corestore API in SDK
- [ ] SDK integration with Cabal
- [ ] dat-gateway + dat-store + hyperswarm-proxy = this should be a thing you deploy for your community or application and should load content the same as beaker 

## Community
- [x] Newsletter (Spring)
- [x] Terms documentation: Describe terms involved in the Dat ecosystem
- [x] Add summary of DTN week to newsletter
- [ ] Organize community to collaborate between the different groups using Dat
  - [x] Send out initial email to orgs
  - [x] Initial meeting - figure out how to collaborate
  - [ ] Find points of collaboration

## Other fun goodies
- [ ] [multi-hyperdrive](https://github.com/RangerMauve/multi-hyperdrive/)
- [ ] Example using [multifeed](https://github.com/kappa-db/multifeed), [corestore](https://github.com/andrewosh/random-access-corestore), and the SDK
- [ ] Fix daemon creation in the dat-store CLI https://github.com/nospaceships/node-os-service/issues/46
- [ ] FUSE on Windows
- [ ] Dat-js integrated with dweb-transports
- [ ] System tray application for Dat
  - [ ] Find open source system tray library
  - [ ] Build off of dat-store for running a storage provider locally
  - [ ] Basic web UI for interacting with the store loaded from localhost
  - [ ] Incorporate dat-gateway for loading websites
  - [ ] incorporate hyperswarm-proxy for browser replication

**Comment by RangerMauve** [comment]
Dat-store is released!

**Comment by RangerMauve** [comment]
There's already documentation for troubleshooting loading data! https://docs.datproject.org/docs/troubleshooting

Gonna skip that step in the TODO list.

**Comment by RangerMauve** [comment]
So, two things before I can improve the dat-js reliability:

- dat-store is having issues with syncing from folders (thanks fleeky)
- I quickly updated [dat-archive-web](https://github.com/RangerMauve/dat-archive-web) so people can add the DatArchive API from Beaker using dat-js under the hood

**Comment by RangerMauve** [comment]
Dat-store is updated in 2.0.9 and people are saying that it's working well. 🎉

Also made a lot of progress on discovery-swarm-stream not advertising Dats created in the browser on the network. Probably finish that up tomorrow. https://github.com/RangerMauve/discovery-swarm-stream/pull/8

**Comment by RangerMauve** [comment]
Progress on first newsletter: https://github.com/datproject/newsletter/pull/5

**Comment by RangerMauve** [comment]
Released the discovery-swarm-stream stuff, it's given dat-js a huge performance boost!

**Comment by RangerMauve** [comment]
What the heck, there's already a terminology page. How did I miss that too?! https://docs.datproject.org/docs/terms

**Comment by RangerMauve** [comment]
Added some more terms to the docs: https://github.com/datproject/docs/pull/154

**Comment by okdistribute** [comment]
regarding the system-tray, that might overlap with some of the daemon work that @andrewosh has been working on, so let's punt on that for now I'd say and try to minimize any duplicate efforts going on by coordinating with the hyperdivision folks

**Comment by RangerMauve** [comment]
So, I've got an initial sketch for cabal-web going: https://github.com/RangerMauve/cabal-web

This helped stress-test discovery-swarm-web and random-access-storage. Part of this involved creating a new discovery-swarm-web gateway which keeps the default discovery-swarm handshake in place for applications that need it (like cabal). This should make it useful for a wider variety of applications.

Next I'm gonna finish up some stuff with dat-store

**Comment by RangerMauve** [comment]
Drafting up May's newsletter now. :)

**Comment by RangerMauve** [comment]
Working on the SDK, gonna get an initial version out there with the DatArchive API, then I'll draft up the new Hyperdrive/Hypercore Beaker stuff.

The initial version will lay down the groundwork for using hyperdiscovery / archive management cross-platform.

**Comment by RangerMauve** [comment]
Alternating between SDK and Mostly Minimal Spanning tree at the moment.

Also doing some organizational stuff for the working group.

**Comment by RangerMauve** [comment]
Fixed a big bug in random-access-web on firefox. Thanks to @gozala and @sammacbeth for helping debug!

First version of the SDK is almost ready to be released. Just waiting on [this hyperdrive PR to be released](https://github.com/mafintosh/hyperdrive/pull/240).

**Comment by RangerMauve** [comment]
First version of the SDK is out BTW

**Comment by DougAnderson444** [comment]
> First version of the SDK is out BTW

Sweet progress, @RangerMauve! Is there an `Link` where we can check it out?

**Comment by DougAnderson444** [comment]
Found it, lol:
[https://github.com/datproject/sdk](https://github.com/datproject/sdk)

**Comment by RangerMauve** [comment]
Oops! Thanks. :P

**Comment by RangerMauve** [comment]
Gonna be updating dat-store to use the SDK to see how it feels to use the new API. 😁

**Comment by okdistribute** [comment]
dogfood ftw!

**Comment by RangerMauve** [comment]
Running into a lot of useful questions already.

- What happens when you close
- How can I delete storage for an archive / core?
- How do I load things in-memory instead

**Comment by RangerMauve** [comment]
Also finding useful changes to add to hyperdrive and getting them PR'd. :D

**Comment by RangerMauve** [comment]
Gonna work on CoreStore stuff for next Wednesday. Based on the notes from [this meeting](https://hackmd.io/LcAQ7Ah9TNunE5BCsvmNCw).

**Comment by RangerMauve** [comment]
Released the newsletter for July

Submitted a PR to hyperdrive v10 to expose extensions and peer events

Planning on getting corestore et all integrated

**Comment by RangerMauve** [comment]
Put together [hyperswarm-proxy](https://github.com/RangerMauve/hyperswarm-proxy).

This will be the first step towards getting hyperswarm to work on the web and the first step to getting dat 2.0 into the SDK 🤩

**Comment by RangerMauve** [comment]
Also, released [dat-store](https://github.com/datproject/dat-store#readme)@4.0.0 which uses the SDK for it's dat-related code.

Fixed some bugs in [universal-dat-storage](https://github.com/RangerMauve/universal-dat-storage/) while I was at it.

**Comment by RangerMauve** [comment]
Gonna quickly whip up [hypertrie-down](https://github.com/RangerMauve/hypertrie-down) to take a bit of a mental break from the SDK and hyperswarm before starting on the next part. :P

**Comment by RangerMauve** [comment]
Actually, before finishing integrating dat@2 into the SDK I'll probably create `universal-dat-archive` which will be like `dat-archive-web`, but will use the SDK and will work in node / beaker / etc.

**Comment by DougAnderson444** [comment]
😍 You're a code machine!! Loving the monologue on all the awesome progress!!

**Comment by RangerMauve** [comment]
Here's the progress on the "universal" dat Archive stuff. https://github.com/datproject/sdk/blob/datarchive/test-promise.js

Gonna turn it into a polyfill style where you just import and get DatArchive with some sane defaults which works across platforms.

**Comment by RangerMauve** [comment]
Pausing dat2 integration in the SDK for a bit to focus on community organizing more, and making dat-store more usable for apps using the SDK (hypercore support)

**Comment by RangerMauve** [comment]
Community organizing going well. We've got a consortium group meeting every two weeks.

Made a few fixes to the SDK to make it work better.

Starting on hyperswarm-web work to progress on Dat2 integration.

**Comment by RangerMauve** [comment]
Regarding system tray applications, started talking to @zootella and @jwerle about the Ara file manager supporting stuff like a local gateway that the SDK could use.

**Comment by RangerMauve** [comment]
Also part of my consortium work has been to transcribe the audio calls into text. Keeping this private to the group for now.

**Comment by RangerMauve** [comment]
Working on dat website redesign with @todrobbins https://github.com/datproject/dat-foundation-website/pull/123

**Comment by RangerMauve** [comment]
Dat website redesign was released.

Got unit tests for hyperswarm-web passing and released the initial version.

Working on a demo for hyperswarm-web/hyperswarm.

Next item is going to be to get Dat-SDK released as 1.0.0 along with docs. https://github.com/datproject/sdk/issues/31

**Comment by RangerMauve** [comment]
Released https://github.com/RangerMauve/hyperswarm-universal-chat to showcase using hyperswarm.

Working on getting the Dat SDK to 1.0. 😁

**Comment by RangerMauve** [comment]
Just an update, I haven't been working for the dat project since February, but I've still been working on dat-sdk and some other projects in my spare time / for other contracts.

Feel free to follow my twitter for updates or reach out to me if you have questions or want to hire me to help you with p2p stuff. 😁
